name: GitHub Actions Demo

on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Declenchement par ${{ github.event_name }}"
      - run: echo "Serveur ${{ runner.os }}"
      - run: echo "Branche ${{ github.ref }} et depot ${{ github.repository }}"
      - run: python job.py